/* Sombreadores de los modelos de Blender: port de tunnelkit.js (losas deformadas a su celda),
 * boxes.js (cajas de piedra con runa y de cristal), stylize.js (luz estilizada) y decor.js
 * (perspectiva aérea). Requiere SH_COMMON_FRAG de shaders.h. */
#ifndef HT_KITSHADERS_H
#define HT_KITSHADERS_H
#include "shaders.h"

/* losas: cada instancia es una celda con sus 4 esquinas y 2 normales (tunnelkit.js: cellPos) */
static const char *VS_CELL =
"uniform mat4 uVP;\n"
"in vec3 aPos; in vec3 aNrm; in vec2 aUv; in vec4 aTan; in vec4 aCol;\n"
"in vec3 aC0; in vec3 aC1; in vec3 aC2; in vec3 aC3; in vec3 aN0; in vec3 aN1; in vec4 aWarn;\n"
"out vec3 vW; out vec3 vN; out vec4 vT; out vec2 vUv; out vec4 vCol; out vec4 vWarn; out float vTile; out float vKz; out vec3 vL;\n"
"void main(){\n"
"  float u = clamp(0.5 - aPos.x / 2.070, -0.1, 1.1), v = aPos.z / 4.0;\n"
"  vec3 a = mix(aC0, aC1, u), b = mix(aC3, aC2, u);\n"
"  vec3 Tx = -normalize(mix(aC1 - aC0, aC2 - aC3, v));\n"
"  vec3 Tz = normalize(b - a);\n"
"  vec3 Ny = normalize(mix(aN0, aN1, v));\n"
"  vec3 p = mix(a, b, v) + Ny * aPos.y;\n"
"  vN = normalize(Tx * aNrm.x + Ny * aNrm.y + Tz * aNrm.z);\n"
"  vT = vec4(normalize(Tx * aTan.x + Ny * aTan.y + Tz * aTan.z), aTan.w);\n"
"  vW = p; vUv = aUv; vCol = aCol; vWarn = aWarn; vKz = v; vL = aPos;\n"
"  vTile = fract(sin(dot(aC0, vec3(12.9898, 78.233, 37.719))) * 43758.5453);\n"
"  gl_Position = uVP * vec4(p, 1.0);\n"
"}\n";

/* objetos sueltos (cajas, costillas, cristales, enredaderas, islas): matriz de modelo */
static const char *VS_MODEL =
"uniform mat4 uVP; uniform mat4 uModel;\n"
"in vec3 aPos; in vec3 aNrm; in vec2 aUv; in vec4 aTan; in vec4 aCol;\n"
"out vec3 vW; out vec3 vN; out vec4 vT; out vec2 vUv; out vec4 vCol; out vec4 vWarn; out float vTile; out float vKz; out vec3 vL;\n"
"void main(){\n"
"  vec4 w = uModel * vec4(aPos, 1.0);\n"
"  mat3 nm = transpose(inverse(mat3(uModel)));\n"
"  vN = normalize(nm * aNrm); vT = vec4(normalize(mat3(uModel) * aTan.xyz), aTan.w);\n"
"  vW = w.xyz; vUv = aUv; vCol = aCol; vWarn = vec4(0.0); vTile = 0.0; vKz = 0.0; vL = aPos;\n"
"  gl_Position = uVP * w;\n"
"}\n";

/* uMode: 0 losa de piedra, 1 losa de cristal, 2 caja de piedra, 3 runa, 4 caja de cristal,
 *        5 adorno (color de vértice), 6 decorado lejano (perspectiva aérea), 7 cascada (alfa) */
static const char *FS_KIT = SH_COMMON_FRAG
"uniform int uMode;\n"
"uniform sampler2D tAlb; uniform sampler2D tNrm; uniform sampler2D tOrm; uniform sampler2D tCAlb; uniform sampler2D tCNrm;\n"
"uniform vec3 uCam; uniform vec3 uFog; uniform float uFogNear; uniform float uFogFar; uniform float uUseFog;\n"
"uniform vec3 uSunDir; uniform vec3 uSunCol; uniform vec3 uShadowCol; uniform vec3 uRimCol; uniform float uRimK;\n"
"uniform vec3 uInlay; uniform vec3 uSeamGlow; uniform vec3 uTint; uniform float uGlowK; uniform float uInvert; uniform vec3 uInvBase; uniform float uHit;\n"
"uniform vec3 uColor; uniform vec3 uEmis; uniform float uGlow; uniform vec3 uBlocks; uniform vec3 uAirCol; uniform float uAlphaK;\n"
"in vec3 vW; in vec3 vN; in vec4 vT; in vec2 vUv; in vec4 vCol; in vec4 vWarn; in float vTile; in float vKz; in vec3 vL;\n"
"out vec4 fragColor;\n"
"vec3 nmap(vec3 N, vec4 T, vec3 t){ vec3 Tn = normalize(T.xyz - N * dot(N, T.xyz)); vec3 B = cross(N, Tn) * T.w; return normalize(mat3(Tn, B, N) * (t * 2.0 - 1.0)); }\n"
/* stylize.js: la sombra toma el color frío del mundo, el sol el suyo, borde fresnel */
"vec3 styl(vec3 base, vec3 N, vec3 V, float ao, float rimK){\n"
"  float ndl = dot(N, uSunDir), sh = smoothstep(0.35, -0.35, ndl) * 0.6;\n"
"  float lb = dot(base, vec3(0.3333));\n"
"  vec3 shade = mix(base * uShadowCol, vec3(lb) * uShadowCol * 1.2, 0.6) + uShadowCol * 0.05;\n"
"  vec3 st = mix(base * uSunCol * (0.9 + 0.3 * max(ndl, 0.0)), shade, sh);\n"
"  st *= mix(1.0, ao, 0.85);\n"
"  st += uRimCol * pow(1.0 - max(dot(N, V), 0.0), 3.0) * rimK * (1.0 - sh * 0.5);\n"
"  return st;\n"
"}\n"
"void main(){\n"
"  vec3 N = normalize(vN); if (!gl_FrontFacing) N = -N;\n"
"  vec3 V = normalize(uCam - vW);\n"
"  vec3 col; float alpha = 1.0;\n"
"  if (uMode == 0) {\n"
"    vec3 alb = texture(tAlb, vUv).rgb; vec3 orm = texture(tOrm, vUv).rgb;\n"
"    vec3 Np = nmap(N, vT, texture(tNrm, vUv).xyz);\n"
"    vec3 base = alb * uTint * (0.94 + 0.12 * vTile) * mix(vec3(1.0), vec3(0.93, 1.02, 0.9), step(0.82, fract(vTile * 7.13)));\n"
"    float isRec = step(1.5, vWarn.x);\n"
"    float ribBand = min(vWarn.x, 1.0) * (1.0 - isRec) * (1.0 - smoothstep(0.075, 0.09, vKz));\n"
"    float ribInlay = min(vWarn.x, 1.0) * (1.0 - isRec) * smoothstep(0.022, 0.03, vKz) * (1.0 - smoothstep(0.05, 0.058, vKz));\n"
"    float recBand = isRec * (smoothstep(0.02, 0.05, vKz) * (1.0 - smoothstep(0.3, 0.33, vKz)) + smoothstep(0.62, 0.65, vKz) * (1.0 - smoothstep(0.95, 0.98, vKz)) * 0.6);\n"
"    base *= 1.0 - 0.28 * ribBand;\n"
"    base = mix(base, vec3(1.0, 0.82, 0.3), recBand * 0.7);\n"
"    col = styl(base, Np, V, orm.r, 0.06);\n"
"    float seamM = (1.0 - smoothstep(0.1, 0.15, dot(alb, vec3(0.2126, 0.7152, 0.0722)))) * step(0.13, vUv.y);\n"
"    col += uInlay * ribInlay * 1.4 + uSeamGlow * seamM + vec3(1.0, 0.75, 0.2) * recBand * 1.1;\n"
"  } else if (uMode == 1) {\n"
"    vec3 ca = texture(tCAlb, vUv).rgb * vCol.rgb;\n"
"    vec3 Np = nmap(N, vT, texture(tCNrm, vUv).xyz);\n"
"    float on = clamp((vWarn.a - 0.42) / 0.58, 0.0, 1.0);\n"
"    float rimC = smoothstep(0.8, 0.95, dot(ca, vec3(0.3333)));\n"
"    vec3 base = ca * mix(mix(vWarn.rgb, vec3(1.0), 0.35), vWarn.rgb * mix(vec3(1.0), vWarn.rgb, 0.6), on);\n"
"    col = styl(base, Np, V, 1.0, 0.6);\n"
"    float fresC = pow(1.0 - abs(dot(Np, V)), 3.0);\n"
"    vec3 glowC = mix(vWarn.rgb, vec3(1.0), 0.35);\n"
"    col += (vWarn.rgb * (0.06 + 0.3 * on) + glowC * rimC * (0.1 + 0.3 * on) + glowC * fresC * (0.08 + 0.15 * on)) * uGlowK;\n"
"  } else if (uMode == 2 || uMode == 4) {\n"
"    vec3 q = fract((vL + 0.5) * uBlocks) - 0.5; vec3 a = abs(q);\n"
"    float mid = a.x + a.y + a.z - max(a.x, max(a.y, a.z)) - min(a.x, min(a.y, a.z));\n"
"    float edge = smoothstep(0.34, 0.44, mid);\n"
"    float fres = pow(1.0 - abs(dot(N, V)), 3.0);\n"
"    if (uMode == 2) {\n"
"      vec3 Np = nmap(N, vT, texture(tNrm, vUv).xyz);\n"
"      vec3 base = texture(tAlb, vUv).rgb * uColor * 0.8;\n"
"      col = styl(base, Np, V, texture(tOrm, vUv).r, 0.35);\n"
"      col += uColor * (0.14 + edge * 1.0 + fres * 0.45);\n"
"    } else {\n"
"      vec3 Np = nmap(N, vT, texture(tCNrm, vUv).xyz);\n"
"      vec3 base = vCol.rgb * uColor;\n"
"      col = styl(base, Np, V, 1.0, 0.7) + uColor * 0.12;\n"
"    }\n"
"  } else if (uMode == 8) {\n"
"    /* moneda de oro (coins.js): metal pulido con reflejo */\n"
"    vec3 gold = uColor; vec3 H = normalize(uSunDir + V); float nv = abs(dot(N, V));\n"
"    col = styl(gold * 0.8, N, V, 1.0, 0.4) + gold * pow(1.0 - nv, 2.0) * 0.6 + vec3(1.0, 0.85, 0.5) * pow(max(dot(N, H), 0.0), 40.0) * 1.2 + uEmis;\n"
"  } else if (uMode == 3) {\n"
"    col = uColor * (1.9 + uGlow * 1.6);\n"
"  } else {\n"
"    vec3 base = vCol.rgb * uColor;\n"
"    col = styl(base, N, V, 1.0, 0.25) + uEmis;\n"
"    if (uMode == 7) alpha = vCol.a * uAlphaK;\n"
"    if (uMode >= 6) {\n"
"      /* decor.js: verdes desaturados, tinte del horizonte y perspectiva aérea con la distancia */\n"
"      float airD = length(uCam - vW);\n"
"      float L = dot(col, vec3(0.2126, 0.7152, 0.0722));\n"
"      col = mix(col, vec3(L), 0.35);\n"
"      col *= mix(vec3(1.0), uAirCol * 1.15, 0.2);\n"
"      col = mix(col, uAirCol, mix(0.15, 0.6, smoothstep(180.0, 600.0, airD)) * smoothstep(60.0, 180.0, airD));\n"
"    }\n"
"  }\n"
"  if (uMode <= 1) {\n"
"    col = mix(col, uInvBase * 0.6, uInvert);\n"
"    col = mix(col, vec3(1.0, 0.25, 0.3), uHit * 0.35);\n"
"  }\n"
"  if (uUseFog > 0.5) col = mix(col, uFog, smoothstep(uFogNear, uFogFar, length(uCam - vW)));\n"
"  if (alpha < 0.01) discard;\n"
"  fragColor = vec4(finish(col), alpha);\n"
"}\n";

/* partículas (life.js) y líneas de velocidad (streaks.js): posición ya calculada, color por vértice */
static const char *VS_FX =
"uniform mat4 uVP;\n"
"in vec3 aPos; in vec3 aNrm; in vec2 aUv; in vec4 aTan; in vec4 aCol;\n"
"out vec2 vUv; out vec4 vCol;\n"
"void main(){ vUv = aUv; vCol = aCol; gl_Position = uVP * vec4(aPos, 1.0); }\n";
static const char *FS_FX = SH_COMMON_FRAG
"uniform int uKind;   /* 0 hoja, 1 punto luminoso, 2 línea */\n"
"in vec2 vUv; in vec4 vCol;\n"
"out vec4 fragColor;\n"
"void main(){\n"
"  float a = vCol.a;\n"
"  if (uKind == 0) { vec2 q = vUv * 2.0 - 1.0; float w = 1.0 - q.y * q.y; if (abs(q.x) > w * 0.95 || abs(q.x) < 0.04 * w) discard; }\n"
"  else if (uKind == 1) { float r = length(vUv * 2.0 - 1.0); a *= smoothstep(1.0, 0.0, r) * (0.5 + 0.5 * smoothstep(0.4, 0.0, r)); }\n"
"  if (a < 0.02) discard;\n"
"  fragColor = vec4(finish(vCol.rgb), a);\n"
"}\n";

#endif
